<?php
/**
 * Site Builder generated theme — functions.php
 *
 * Wires up the basic theme features that the Site Builder plugin expects:
 *   - menu locations 'primary' and 'footer' (so the plugin's Settings dropdowns
 *     can attach Main Auto Menu / Footer Auto Menu automatically)
 *   - custom_logo support (so logo.png from FSR archives is rendered by the theme)
 *   - title-tag + post-thumbnails + html5
 *
 * Generated by Site Builder plugin — do not edit directly. Regenerate via the
 * "Тема" tab in the plugin admin to pick a different combination of header/
 * footer/styles. Manual edits will be overwritten on the next regeneration.
 */

if (!defined('ABSPATH')) exit;

// Theme add-on modules. i18n is loaded first because the other modules
// (and header/footer templates) may call sb_t(). Each module wraps its
// functions in function_exists() guards so duplicate loads are safe.
$sb_inc_dir = __DIR__ . '/inc';
foreach (['i18n.php', 'shortcodes.php', 'link-resolver.php', 'similar-post.php', 'geo-shortcodes.php', 'articles-grid.php', 'breadcrumbs.php', 'external-links.php', 'sitemap.php', 'blocks.php', 'seo.php', 'back-to-top.php'] as $sb_inc_file) {
    $sb_inc_path = $sb_inc_dir . '/' . $sb_inc_file;
    if (file_exists($sb_inc_path)) require_once $sb_inc_path;
}
unset($sb_inc_dir, $sb_inc_file, $sb_inc_path);

if (!function_exists('sb_theme_setup')) {
    function sb_theme_setup() {
        add_theme_support('title-tag');
        add_theme_support('post-thumbnails');
        add_theme_support('html5', ['search-form', 'comment-form', 'comment-list', 'gallery', 'caption']);
        add_theme_support('custom-logo', [
            'height'      => 80,
            'width'       => 240,
            'flex-height' => true,
            'flex-width'  => true,
        ]);
        register_nav_menus([
            'primary' => function_exists('sb_t') ? sb_t('primary_menu') : 'Primary menu',
            'footer'  => function_exists('sb_t') ? sb_t('footer_menu')  : 'Footer menu',
        ]);
    }
    add_action('after_setup_theme', 'sb_theme_setup');
}

if (!function_exists('sb_theme_enqueue')) {
    function sb_theme_enqueue() {
        $stylesheet_uri = get_stylesheet_uri();
        $stylesheet_path = get_stylesheet_directory() . '/style.css';
        $ver = file_exists($stylesheet_path) ? (string)filemtime($stylesheet_path) : '1.0';
        wp_enqueue_style('sb-theme-style', $stylesheet_uri, [], $ver);
        // Theme JS is assembled from header/footer variant .js files by the
        // plugin's theme generator. It's only emitted if at least one variant
        // shipped a JS companion; otherwise the file is absent and we skip
        // enqueueing to keep the page lean.
        $js_path = get_stylesheet_directory() . '/assets/theme.js';
        if (file_exists($js_path)) {
            $js_uri = get_stylesheet_directory_uri() . '/assets/theme.js';
            $js_ver = (string)filemtime($js_path);
            wp_enqueue_script('sb-theme-js', $js_uri, [], $js_ver, true); // in footer
        }
    }
    add_action('wp_enqueue_scripts', 'sb_theme_enqueue');
}
