<?php
/**
 * Site Builder generated theme — functions.php
 *
 * Wires up the basic theme features that the Site Builder plugin expects:
 *   - menu locations 'primary' and 'footer' (so the plugin's Settings dropdowns
 *     can attach Main Auto Menu / Footer Auto Menu automatically)
 *   - custom_logo support (so logo.png from FSR archives is rendered by the theme)
 *   - title-tag + post-thumbnails + html5
 *
 * Generated by Site Builder plugin — do not edit directly. Regenerate via the
 * "Тема" tab in the plugin admin to pick a different combination of header/
 * footer/styles. Manual edits will be overwritten on the next regeneration.
 */

if (!defined('ABSPATH')) exit;

if (!function_exists('sb_theme_setup')) {
    function sb_theme_setup() {
        add_theme_support('title-tag');
        add_theme_support('post-thumbnails');
        add_theme_support('html5', ['search-form', 'comment-form', 'comment-list', 'gallery', 'caption']);
        add_theme_support('custom-logo', [
            'height'      => 80,
            'width'       => 240,
            'flex-height' => true,
            'flex-width'  => true,
        ]);
        register_nav_menus([
            'primary' => 'Основное меню',
            'footer'  => 'Меню в подвале',
        ]);
    }
    add_action('after_setup_theme', 'sb_theme_setup');
}

if (!function_exists('sb_theme_enqueue')) {
    function sb_theme_enqueue() {
        $stylesheet_uri = get_stylesheet_uri();
        $stylesheet_path = get_stylesheet_directory() . '/style.css';
        $ver = file_exists($stylesheet_path) ? (string)filemtime($stylesheet_path) : '1.0';
        wp_enqueue_style('sb-theme-style', $stylesheet_uri, [], $ver);
    }
    add_action('wp_enqueue_scripts', 'sb_theme_enqueue');
}
