<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Resolves image references in FSR archive content to real files on disk,
 * uploads them to the WordPress media library, and rewrites <img src=""> in
 * page HTML to point at the uploaded WP URLs.
 *
 * Lookup strategy (in order, first match wins):
 *   1. Original src interpreted as path relative to the page's index file
 *      (this is how authors usually write it: ../IMAGES/foo.webp)
 *   2. Same basename inside the archive's top-level IMAGES/ folder
 *   3. Same basename inside the page's own folder
 *   4. Same basename anywhere under the archive root (recursive)
 *   5. Not found → image is left with its original src, a warning is logged
 *
 * Every successful resolution is cached so re-references (same image used by
 * several pages) only do one upload and one media library entry — Media_Handler
 * additionally deduplicates by content hash, but caching the resolver result
 * also avoids the disk re-scan.
 */
class Site_Builder_FSR_Image_Resolver {

    private Site_Builder_Media_Handler $media;
    private string $archive_root;
    /** Cache of absolute_filepath => attachment_id (or null if upload failed). */
    private array $upload_cache = [];
    /** Cache of basename => absolute_filepath (or null if not found anywhere). */
    private array $find_cache = [];
    /** Warnings collected during this resolver's lifetime (one per missing image). */
    public array $warnings = [];

    public function __construct(Site_Builder_Media_Handler $media, string $archive_root) {
        $this->media = $media;
        $this->archive_root = rtrim($archive_root, '/');
    }

    /**
     * Process HTML content: find every <img src="...">, try to resolve and upload
     * each one, rewrite src to the WP URL on success. Returns the rewritten HTML
     * plus stats (found, uploaded, missing).
     *
     * The HTML is generated by md_to_html() and so uses straight quotes only;
     * we still match both single and double quotes defensively in case future
     * markdown extensions emit single-quoted attributes.
     *
     * @param string $html         HTML content of the page (after md_to_html)
     * @param string $page_dir     Absolute path to the page's folder (or archive root for the front page)
     * @return array               ['html'=>string, 'found'=>int, 'uploaded'=>int, 'missing'=>int]
     */
    public function process_content(string $html, string $page_dir): array {
        $stats = ['found' => 0, 'uploaded' => 0, 'missing' => 0];

        $rewritten = preg_replace_callback(
            '/<img\b([^>]*?)src=(["\'])([^"\'>]+)\2([^>]*)>/i',
            function ($m) use ($page_dir, &$stats) {
                $stats['found']++;
                $before = $m[1];
                $quote  = $m[2];
                $src    = $m[3];
                $after  = $m[4];

                // Skip absolute URLs (http/https) and data URIs — leave as is
                if (preg_match('#^(https?:|data:|//)#i', $src)) {
                    return $m[0];
                }

                $alt = '';
                if (preg_match('/\balt=(["\'])([^"\']*)\1/i', $before . $after, $am)) {
                    $alt = $am[2];
                }

                $resolved = $this->resolve_src($src, $page_dir);
                if ($resolved === null) {
                    $stats['missing']++;
                    $this->warnings[] = "Не найдена картинка: '{$src}' (страница: {$page_dir})";
                    return $m[0];
                }

                $attach_id = $this->upload_resolved($resolved, $alt);
                if (!$attach_id) {
                    $stats['missing']++;
                    $this->warnings[] = "Не удалось загрузить: '{$resolved}'";
                    return $m[0];
                }

                $stats['uploaded']++;
                $new_url = wp_get_attachment_url($attach_id);
                if (!$new_url) return $m[0];

                return '<img' . $before . 'src=' . $quote . esc_url($new_url) . $quote . $after . '>';
            },
            $html
        );

        return ['html' => $rewritten, 'found' => $stats['found'], 'uploaded' => $stats['uploaded'], 'missing' => $stats['missing']];
    }

    /**
     * Upload a single image given its raw src reference (the way it appears in
     * frontmatter, e.g. "../IMAGES/foo.webp"). Used for featured images (headimg)
     * and other one-off uploads not embedded in HTML.
     *
     * @return int|null  Attachment ID, or null if the file couldn't be resolved/uploaded.
     */
    public function resolve_and_upload(string $src, string $page_dir, string $alt = ''): ?int {
        $resolved = $this->resolve_src($src, $page_dir);
        if ($resolved === null) {
            $this->warnings[] = "Не найдена картинка: '{$src}' (страница: {$page_dir})";
            return null;
        }
        return $this->upload_resolved($resolved, $alt);
    }

    /**
     * Resolve a raw src into an absolute file path on disk, applying the lookup
     * strategy. Returns null if no match anywhere.
     */
    private function resolve_src(string $src, string $page_dir): ?string {
        $src = trim($src);
        if ($src === '') return null;

        // 1. Path relative to the page's own folder
        $candidate = $this->realpath_safe(rtrim($page_dir, '/') . '/' . $src);
        if ($candidate !== null && is_file($candidate)) {
            return $candidate;
        }

        // 2..4: search by basename anywhere we know to look
        $basename = basename($src);
        if ($basename === '' || $basename === '.' || $basename === '..') return null;

        if (array_key_exists($basename, $this->find_cache)) {
            return $this->find_cache[$basename];
        }

        // 2. archive_root/IMAGES/<basename>
        $images_dir = $this->archive_root . '/IMAGES';
        if (is_dir($images_dir)) {
            $candidate = $images_dir . '/' . $basename;
            if (is_file($candidate)) {
                $this->find_cache[$basename] = $candidate;
                return $candidate;
            }
        }

        // 3. page_dir/<basename>
        $candidate = rtrim($page_dir, '/') . '/' . $basename;
        if (is_file($candidate)) {
            $this->find_cache[$basename] = $candidate;
            return $candidate;
        }

        // 4. recursive scan of archive_root
        $found = $this->recursive_find($this->archive_root, $basename);
        $this->find_cache[$basename] = $found;
        return $found;
    }

    /**
     * Build an absolute path with .. components resolved, WITHOUT requiring the
     * file to exist (realpath() returns false for non-existent paths, which we
     * don't want — we want the normalised path so we can then test is_file()).
     */
    private function realpath_safe(string $path): ?string {
        // Use realpath if dir exists, else manually normalise
        $real = @realpath($path);
        if ($real !== false) return $real;

        // Fallback: manually collapse "/./" and "/../"
        $parts = [];
        foreach (explode('/', $path) as $seg) {
            if ($seg === '' || $seg === '.') continue;
            if ($seg === '..') {
                if (!empty($parts)) array_pop($parts);
                continue;
            }
            $parts[] = $seg;
        }
        $normalised = ($path[0] === '/' ? '/' : '') . implode('/', $parts);
        return $normalised !== '' ? $normalised : null;
    }

    /**
     * Recursively walk $dir looking for a file with the given basename. Returns
     * the absolute path or null. Skips the same service folders the scanner
     * ignores (PROMTS, .git, etc.) to keep traversal cheap.
     */
    private function recursive_find(string $dir, string $basename): ?string {
        static $skip = ['.git' => 1, 'node_modules' => 1, '__MACOSX' => 1, '.DS_Store' => 1, 'PROMTS' => 1, 'PROMPTS' => 1];
        $items = @scandir($dir);
        if (!$items) return null;
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') continue;
            if (isset($skip[$item]) || isset($skip[strtoupper($item)])) continue;
            $full = $dir . '/' . $item;
            if (is_file($full) && $item === $basename) return $full;
            if (is_dir($full)) {
                $rec = $this->recursive_find($full, $basename);
                if ($rec !== null) return $rec;
            }
        }
        return null;
    }

    /**
     * Upload a resolved file path through Media_Handler, with our own caching
     * on top so the same absolute path is only uploaded once per import.
     */
    private function upload_resolved(string $absolute_path, string $alt_text = ''): ?int {
        if (array_key_exists($absolute_path, $this->upload_cache)) {
            return $this->upload_cache[$absolute_path];
        }
        $attach_id = $this->media->upload_image($absolute_path, $alt_text);
        $this->upload_cache[$absolute_path] = $attach_id;
        return $attach_id;
    }
}
